### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by jotasolano** [jotasolano/cAlign#7]
Get a loader for when a dataset is being loaded and parsed. Something with animated squares could be good for the theme

**Comment by carcruz** [comment]
Loader component add it on commit [#80](https://github.com/jotasolano/cAlign/commit/4d3f3562734821ad0b23070026ebbbe0b01fe05b). To modify styles go to `client/source/ShareComponents/Loader/style`.
Loader based in [SpinKit](https://github.com/tobiasahlin/SpinKit) (waves)
